# Generated by Django 4.1.5 on 2023-02-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_username', models.CharField(max_length=50)),
                ('customer_email', models.CharField(max_length=50)),
                ('customer_password', models.CharField(max_length=50)),
            ],
        ),
    ]
