# Generated by Django 4.1.5 on 2023-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('room_capacity', models.CharField(max_length=50)),
                ('room_photo', models.ImageField(upload_to='room/')),
                ('room_price', models.CharField(max_length=100)),
                ('room_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
