# Generated by Django 4.1.5 on 2023-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resort_admin', '0002_add_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('aadhaar_card', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('agg', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='staff/')),
            ],
        ),
    ]
